### ISSUE TITLE
How to access the endpoint?

### ISSUE THREAD

**Issue by DmanAwesome1** [otherwiseDE/DiscordTwitterBot#2]
[TWITTER] Starting Service
[TWITTER] Following Twitter User @VGTeamGG
For Support please join https://discord.gg/PrGCCWpDbP
Oh no
Encountered an unrecoverable error, the stream is abort.
  Reason: [ 403 ] The connecting account is not permitted to access this endpoint.
  Please refer to https://dev.twitter.com/streaming/overview/connecting to debug your request parameters.
[TWITTER] Service Started

**Comment by DisPlume** [comment]
https://twitter.com/TwitterAPI/status/1520089464487436297
It might be the cause of it... I have tried many other bots, and they all gave me 403 error when legacy v1.1 streaming endpoints is involved.

**Comment by DmanAwesome1** [comment]
Ok. What do you recommend?

**Comment by DmanAwesome1** [comment]
??

**Comment by otherwiseGG** [comment]
Hey,

I'm sorry for the late response there's currently alot going on.
Please make sure to apply for elevated Access -  Try using Standalone Apps / Creating new Projects.

This is occuring lately pretty often because as you said, the legacy v1.1 Endpoints are outdated.
Unfortunately, i'm not the creator of the Node Packages so i have no control of what Endpoints are being used.

**Comment by intersecato** [comment]
I have the same issue but I already applieed for elevated access
